### ISSUE TITLE
WebRTC 프로젝트 환경 컴파일 오류 발생: AttributeError: 'JNIFromJavaP' object has no attribute 'fully_qualified_class'

### ISSUE THREAD

**Issue by Kanteloper** [Kanteloper/avatar_android_app#16]
## Problem
```
ninja: Entering directory `out/Debug'
[9/6162] ACTION //sdk/android:generated_external...ist(//build/toolchain/android:android_clang_arm)
FAILED: gen/sdk/android/generated_external_classes_jni/jni/ArrayList_jni.h 
python ../../base/android/jni_generator/jni_generator.py --jar_file ../../third_party/android_tools/sdk/platforms/android-28/android.jar --input_file java/util/ArrayList.class --ptr_type=long --output_dir gen/sdk/android/generated_external_classes_jni/jni --includes ../../../../../../../sdk/android/src/jni/jni_generator_helper.h
Traceback (most recent call last):
  File "../../base/android/jni_generator/jni_generator.py", line 1532, in <module>
    sys.exit(main(sys.argv))
  File "../../base/android/jni_generator/jni_generator.py", line 1528, in main
    GenerateJNIHeader(input_file, output_file, options)
  File "../../base/android/jni_generator/jni_generator.py", line 1430, in GenerateJNIHeader
    jni_from_javap = JNIFromJavaP.CreateFromClass(input_file, options)
  File "../../base/android/jni_generator/jni_generator.py", line 803, in CreateFromClass
    jni_from_javap = JNIFromJavaP(stdout.split('\n'), options)
  File "../../base/android/jni_generator/jni_generator.py", line 728, in __init__
    self.fully_qualified_class = self.fully_qualified_class.replace('.', '/')
AttributeError: 'JNIFromJavaP' object has no attribute 'fully_qualified_class'
[11/6162] ACTION //sdk/android:generated_externa...ger(//build/toolchain/android:android_clang_arm)
FAILED: gen/sdk/android/generated_external_classes_jni/jni/BigInteger_jni.h 
python ../../base/android/jni_generator/jni_generator.py --jar_file ../../third_party/android_tools/sdk/platforms/android-28/android.jar --input_file java/math/BigInteger.class --ptr_type=long --output_dir gen/sdk/android/generated_external_classes_jni/jni --includes ../../../../../../../sdk/android/src/jni/jni_generator_helper.h
Traceback (most recent call last):
  File "../../base/android/jni_generator/jni_generator.py", line 1532, in <module>
    sys.exit(main(sys.argv))
  File "../../base/android/jni_generator/jni_generator.py", line 1528, in main
    GenerateJNIHeader(input_file, output_file, options)
  File "../../base/android/jni_generator/jni_generator.py", line 1430, in GenerateJNIHeader
    jni_from_javap = JNIFromJavaP.CreateFromClass(input_file, options)
  File "../../base/android/jni_generator/jni_generator.py", line 803, in CreateFromClass
    jni_from_javap = JNIFromJavaP(stdout.split('\n'), options)
  File "../../base/android/jni_generator/jni_generator.py", line 728, in __init__
    self.fully_qualified_class = self.fully_qualified_class.replace('.', '/')
AttributeError: 'JNIFromJavaP' object has no attribute 'fully_qualified_class'
[14/6162] ACTION //sdk/android:generated_externa...ean(//build/toolchain/android:android_clang_arm)
FAILED: gen/sdk/android/generated_external_classes_jni/jni/Boolean_jni.h 
python ../../base/android/jni_generator/jni_generator.py --jar_file ../../third_party/android_tools/sdk/platforms/android-28/android.jar --input_file java/lang/Boolean.class --ptr_type=long --output_dir gen/sdk/android/generated_external_classes_jni/jni --includes ../../../../../../../sdk/android/src/jni/jni_generator_helper.h
Traceback (most recent call last):
  File "../../base/android/jni_generator/jni_generator.py", line 1532, in <module>
    sys.exit(main(sys.argv))
  File "../../base/android/jni_generator/jni_generator.py", line 1528, in main
    GenerateJNIHeader(input_file, output_file, options)
  File "../../base/android/jni_generator/jni_generator.py", line 1430, in GenerateJNIHeader
    jni_from_javap = JNIFromJavaP.CreateFromClass(input_file, options)
  File "../../base/android/jni_generator/jni_generator.py", line 803, in CreateFromClass
    jni_from_javap = JNIFromJavaP(stdout.split('\n'), options)
  File "../../base/android/jni_generator/jni_generator.py", line 728, in __init__
    self.fully_qualified_class = self.fully_qualified_class.replace('.', '/')
AttributeError: 'JNIFromJavaP' object has no attribute 'fully_qualified_class'
ninja: build stopped: subcommand failed.

```
에러 메시지를 보면, Java나 python 패키지를 찾지 못해서 발생하는 것 같다.

**Comment by Kanteloper** [comment]
../../base/android/jni_generator/jni_generator/jni_generator.py 파일에서 코드 분석해보니 
python 버전 문제는 아닌 듯 하다.

**Comment by Kanteloper** [comment]
[https://groups.google.com/d/msg/discuss-webrtc/t3VLQl8IMEc/f8ZM1DDECgAJ](https://groups.google.com/d/msg/discuss-webrtc/t3VLQl8IMEc/f8ZM1DDECgAJ)

**Comment by Kanteloper** [comment]
ninja로 빌드 시, ninja가 javap를 찾지 못하는 것이 원인 인 듯 하다.

**Comment by Kanteloper** [comment]
어떤 중국 놈이 동일한 이슈에 대한 답변으로 java CLASSPATH를 unset하라고 했는데, 해봐도 해결되지 않는다.

**Comment by Kanteloper** [comment]
## SOLVED
- CLASSPATH를 현재 디렉토리인 "./"로 설정
- zshrc 설정 파일에 export PATH=${PATH}:${JAVA_HOME}/bin/javap  추가함.
